name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Scoop - setup - build
        shell: pwsh
        run: |
            Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
            Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
            scoop bucket add openttd https://github.com/WenSimEHRP/OpenTTD-Bucket
            scoop install openttd/nml
            scoop install openttd/gorender
            make

      - uses: actions/upload-artifact@v4
        with:
          name: chinasettrains.grf
          path: chinasettrains.grf
